# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id_comentario', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('comentario', models.TextField(max_length=600)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id_evento', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('sub_titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(max_length=2000)),
                ('imagen', models.ImageField(upload_to='imagenesEvento/%Y/%m/%d')),
                ('video', models.FileField(upload_to='videosEvento/%Y/%m/%d')),
                ('tags', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('estatus', models.BooleanField()),
                ('valoracion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('coordenada1', models.CharField(max_length=60)),
                ('coordenada2', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id_noticias', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('sub_titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(max_length=2000)),
                ('imagen', models.ImageField(upload_to='imagenesNoticia/%Y/%m/%d', verbose_name='Imagen')),
                ('video', models.FileField(upload_to='videosNoticia/%Y/%m/%d', verbose_name='Video')),
                ('tags', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('estatus', models.BooleanField()),
                ('valoracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id_recurso', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('sub_titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(max_length=2000)),
                ('imagen', models.ImageField(upload_to='imagenesRecurso/%Y/%m/%d')),
                ('video', models.FileField(upload_to='videosRecurso/%Y/%m/%d')),
                ('tags', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('estatus', models.BooleanField()),
                ('valoracion', models.IntegerField()),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_eventos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.evento'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_noticias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.noticia'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_recursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.recurso'),
        ),
    ]
