# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEventos', '0002_auto_20160922_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_eventos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.evento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_noticias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.noticia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_recursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appEventos.recurso'),
        ),
    ]
